### ISSUE TITLE
中文显示乱码

### ISSUE THREAD

**Issue by jgaxmey** [saralmira/ra2-AIwidgets#3]
我原来的aimd.ini里的中文在ai编辑器里打开变成了乱码，我尝试把一个乱码重新输入并保存发布，用文本编辑器打开文件查看，发现新修改的显示正常，以前的中文都是乱码了。我又在文本编辑器点击编码，能看到变成了使用ansi打开，改回utf8，原来的内容变正常，但新加的变乱码

**Comment by jgaxmey** [comment]
![PixPin_2024-07-11_01-33-10](https://github.com/saralmira/ra2-AIwidgets/assets/15307075/1063a521-2c71-4cc8-bc1b-56af7bcb9f84)
超时空兵攻击 是在ai编辑器里重新输入的
@saralmira

**Comment by saralmira** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by saralmira** [comment]
这是因为你之前在文件中使用ANSI编码保存中文字符。
如果要使用中文命名，建议将文件转为utf-8编码后再使用编辑器编辑，编辑器默认以utf-8编码打开文件。

**Comment by jgaxmey** [comment]
@saralmira 不是，我原来的文件是utf-8的。我用ai编辑器新建个文件，输入中文名字，保存发布，再用文本编辑器打开查看编码，是ANSI的。
![2](https://github.com/user-attachments/assets/5a55cd12-9e02-4a4c-b65e-1b57b62377ca)
![3](https://github.com/user-attachments/assets/bebc8812-23f7-4c80-8439-7bebd8a8b198)
![1](https://github.com/user-attachments/assets/eef31645-1855-44c4-852f-86f560d4a537)
